### ISSUE TITLE
the website link is 404

### ISSUE THREAD

**Issue by alick** [gvanrossum/gvanrossum.github.io#10]
I'm not sure what github has done, but your website link https://gvanrossum.github.io is 404 to me. This means all the links for BDFL on docs.python.org are 404 as well :(
<img width="968" alt="Screen Shot 2021-03-27 at 16 20 14 " src="https://user-images.githubusercontent.com/933935/112737522-5b60f500-8f18-11eb-8ceb-81cd2a4a1f1f.png">

**Comment by gvanrossum** [comment]
Hm, this is probably due to recently renaming master to main. I don't know how to fix it, renaming back to master doesn't do the trick. Maybe it's a GitHub issue?

**Comment by gvanrossum** [comment]
Well, I created a master branch, identical to main, and now it works again.

**Comment by gvanrossum** [comment]
I changed a setting in Setting -> Options -> GitHub Pages and now it builds from main, as proven by a small comment I added at the top of the page.
