### ISSUE TITLE
Link to a non-existent website

### ISSUE THREAD

**Issue by JKearnsl** [gvanrossum/gvanrossum.github.io#27]
Hello, I discovered that the specified website (http://www.cnpbagwell.com/audio-faq) does not exist.

```html
FAQ.  It is now maintained by Chris Bagwell
at <A HREF="http://www.cnpbagwell.com/audio-faq"
>http://www.cnpbagwell.com/audio-faq</A>.  And here is a link to
```

[source](https://github.com/gvanrossum/gvanrossum.github.io/blob/main/index.html#L105-L106C22) 🐢

**Comment by gvanrossum** [comment]
Thanks -- I've "fixed" this by linking to the last known good version on archive.org.
